global:
  cacheTTL: 10
  hostname: ${HOSTNAME}
services:
  logging:
    active: True
    default: INFO
  mqtt:
    host: 192.168.1.5
    port: 1883
    baseOutTopic: home/raspi
    inTopic: home/raspi
  temperature:
    active: False
    gpioPin: 4
    sensorType: "DHT22"
    pollInterval: 30
    publishInterval: 600
    temperatureTolerance: 0.5
    humidityTolerance: 4
    humidityCorrection40: 0
    humidityCorrection75: 0
    temperatureCorrection: 0
    humidityTolerance: 4
    appendHostnameToTopic: True
  binarySensor:
    active: False
    sensors:
      - id: "reed"
        gpioPin: 21
        pullDirection: "up"
        labelHigh: "Open"
        labelLow: "Closed"
        mqttTopic: "reed"

      - id: "pir"
        gpioPin: 23
        pullDirection: "down"
        labelHigh: "Motion"
        labelLow: "No Motion"
        mqttTopic: "pir"
  camera:
    active: False
    resolution: [1920, 1080]
    quality: 85
    storagePath: "/tmp/camera"
    mqttTopic: "camera"
    mqttFlags: "ADD_BASE_TOPIC,ADD_HOSTNAME,ADD_TIMESTAMP"
  healthcheck:
    active: False
  update:
    active: True
    repoUrl: "https://homuncu.manhart.space/dl"
    type: stable
    autoupdate: "Off"
  squeezebox:
    active: False
    lmsServer: ""
  readonly:
    active: False
  shutdown:
    active: False
    viaMqtt: False
    viaButton: True
    gpioPin: 3
    pullDirection: "up"
  ipaddress:
    active: False
    mqttFlags: NONE
  git:
    active: False
    repos:
      - name: "repo1"
        path: "~/test-git-repo1"
      - name: "repo2"
        path: "~/test-git-repo2"
      - name: "ssh"
        path: "/home/manuel/.ssh"
